// data.js
const typeWeaknesses = {
    Normal: ["Fighting"],
    Fire: ["Water", "Ground", "Rock"],
    Water: ["Electric", "Grass"],
    Electric: ["Ground"],
    Grass: ["Fire", "Ice", "Poison", "Flying", "Bug"],
    Ice: ["Fire", "Fighting", "Rock", "Steel"],
    Fighting: ["Flying", "Psychic", "Fairy"],
    Poison: ["Ground", "Psychic"],
    Ground: ["Water", "Grass", "Ice"],
    Flying: ["Electric", "Ice", "Rock"],
    Psychic: ["Bug", "Ghost", "Dark"],
    Bug: ["Fire", "Flying", "Rock"],
    Rock: ["Water", "Grass", "Fighting", "Ground", "Steel"],
    Ghost: ["Ghost", "Dark"],
    Dragon: ["Ice", "Dragon", "Fairy"],
    Dark: ["Fighting", "Bug", "Fairy"],
    Steel: ["Fire", "Fighting", "Ground"],
    Fairy: ["Poison", "Steel"],
};

const typeResistances = {
    Normal: [],
    Fire: ["Fire", "Grass", "Ice", "Bug", "Steel", "Fairy"],
    Water: ["Fire", "Water", "Ice", "Steel"],
    Electric: ["Electric", "Flying", "Steel"],
    Grass: ["Water", "Electric", "Grass", "Ground"],
    Ice: ["Ice"],
    Fighting: ["Bug", "Rock", "Dark"],
    Poison: ["Grass", "Fighting", "Poison", "Bug", "Fairy"],
    Ground: ["Poison", "Rock"],
    Flying: ["Grass", "Fighting", "Bug"],
    Psychic: ["Fighting", "Psychic"],
    Bug: ["Grass", "Fighting", "Ground"],
    Rock: ["Normal", "Fire", "Poison", "Flying"],
    Ghost: ["Poison", "Bug"],
    Dragon: ["Fire", "Water", "Electric", "Grass"],
    Dark: ["Ghost", "Dark"],
    Steel: [
        "Normal",
        "Grass",
        "Ice",
        "Flying",
        "Psychic",
        "Bug",
        "Rock",
        "Dragon",
        "Steel",
        "Fairy",
    ],
    Fairy: ["Fighting", "Bug", "Dark"],
};


const typeImmunities = {
    Normal: ["Ghost"],
    Ground: ["Electric"],
    Flying: ["Ground"],
    Ghost: ["Normal", "Fighting"],
    Steel: ["Poison"],
    Dark: ["Psychic"],
    Fairy: ["Dragon"],
};


const typeStrengths = {
    Normal: [],
    Fire: ["Grass", "Ice", "Bug", "Steel"],
    Water: ["Fire", "Ground", "Rock"],
    Electric: ["Water", "Flying"],
    Grass: ["Water", "Ground", "Rock"],
    Ice: ["Grass", "Ground", "Flying", "Dragon"],
    Fighting: ["Normal", "Ice", "Rock", "Dark", "Steel"],
    Poison: ["Grass", "Fairy"],
    Ground: ["Fire", "Electric", "Poison", "Rock", "Steel"],
    Flying: ["Grass", "Fighting", "Bug"],
    Psychic: ["Fighting", "Poison"],
    Bug: ["Grass", "Psychic", "Dark"],
    Rock: ["Fire", "Ice", "Flying", "Bug"],
    Ghost: ["Psychic", "Ghost"],
    Dragon: ["Dragon"],
    Dark: ["Psychic", "Ghost"],
    Steel: ["Ice", "Rock", "Fairy"],
    Fairy: ["Fighting", "Dragon", "Dark"],
};